// Mapowanie krajów do kontynentów
export const countryToContinent = {
	// Europa
	Poland: 'Europe',
	Spain: 'Europe',
	Italy: 'Europe',
	France: 'Europe',
	Germany: 'Europe',
	'United Kingdom': 'Europe',
	Portugal: 'Europe',
	Greece: 'Europe',
	Netherlands: 'Europe',
	Belgium: 'Europe',
	Switzerland: 'Europe',
	Austria: 'Europe',
	'Czech Republic': 'Europe',
	Sweden: 'Europe',
	Norway: 'Europe',
	Denmark: 'Europe',
	Finland: 'Europe',
	Ireland: 'Europe',
	Croatia: 'Europe',
	Hungary: 'Europe',
	Romania: 'Europe',

	// Azja
	Japan: 'Asia',
	China: 'Asia',
	Thailand: 'Asia',
	'South Korea': 'Asia',
	Vietnam: 'Asia',
	Singapore: 'Asia',
	India: 'Asia',
	Indonesia: 'Asia',
	Malaysia: 'Asia',
	Philippines: 'Asia',
	Taiwan: 'Asia',
	'Hong Kong': 'Asia',

	// Ameryka Północna
	'United States': 'North America',
	Canada: 'North America',
	Mexico: 'North America',

	// Ameryka Południowa
	Brazil: 'South America',
	Argentina: 'South America',
	Chile: 'South America',
	Peru: 'South America',
	Colombia: 'South America',
	Ecuador: 'South America',

	// Afryka
	Egypt: 'Africa',
	Morocco: 'Africa',
	'South Africa': 'Africa',
	Kenya: 'Africa',
	Tanzania: 'Africa',
	Tunisia: 'Africa',

	// Oceania
	Australia: 'Oceania',
	'New Zealand': 'Oceania',
	Fiji: 'Oceania',
}

// Funkcja pomocnicza - zwraca kontynent dla kraju
export const getContinent = country => {
	return countryToContinent[country] || 'Unknown'
}

// Funkcja pomocnicza - zwraca unikalne kontynenty z listy krajów
export const getUniqueContinents = countries => {
	const continents = countries.map(country => getContinent(country)).filter(continent => continent !== 'Unknown')

	// Usuń duplikaty używając Set
	return [...new Set(continents)]
}

// Lista wszystkich krajów świata (195 krajów)
export const allCountries = [
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Antigua and Barbuda',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia and Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Cape Verde',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Colombia',
	'Comoros',
	'Congo',
	'Costa Rica',
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czech Republic',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'East Timor',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Ethiopia',
	'Fiji',
	'Finland',
	'France',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Grenada',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Guyana',
	'Haiti',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Ivory Coast',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Macedonia',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Marshall Islands',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Micronesia',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia',
	'Nauru',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Korea',
	'Norway',
	'Oman',
	'Pakistan',
	'Palau',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saint Kitts and Nevis',
	'Saint Lucia',
	'Saint Vincent and the Grenadines',
	'Samoa',
	'San Marino',
	'Sao Tome and Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia',
	'South Africa',
	'South Korea',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Swaziland',
	'Sweden',
	'Switzerland',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Thailand',
	'Togo',
	'Tonga',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Vatican City',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabwe',
]

// Funkcja sprawdzająca czy kraj istnieje
export const isValidCountry = countryName => {
	return allCountries.some(country => country.toLowerCase() === countryName.toLowerCase())
}
